# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attivita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=30, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Attività',
                'verbose_name_plural': 'Attività',
            },
        ),
        migrations.CreateModel(
            name='Cantiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField(max_length=100, verbose_name='Descrizione')),
                ('indirizzo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Indirizzo')),
            ],
            options={
                'verbose_name': 'Cantiere',
                'verbose_name_plural': 'Cantieri',
            },
        ),
        migrations.CreateModel(
            name='CategoriaAttivita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=30, verbose_name='Nome')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ore.CategoriaAttivita')),
            ],
            options={
                'verbose_name': "Categoria dell'attività",
                'verbose_name_plural': 'Categorie delle attività',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=30, verbose_name='Nome')),
                ('cognome', models.TextField(blank=True, max_length=30, null=True, verbose_name='Cognome')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Telefono principale')),
                ('indirizzo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Indirizzo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
            },
        ),
        migrations.CreateModel(
            name='Dipendente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=30, verbose_name='Nome')),
                ('cognome', models.TextField(max_length=30, verbose_name='Cognome')),
            ],
            options={
                'verbose_name': 'Dipendente',
                'verbose_name_plural': 'Dipendenti',
            },
        ),
        migrations.CreateModel(
            name='SchedaAttivita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ore', models.IntegerField(verbose_name='Ore Lavorative')),
                ('ext_preventivo', models.BooleanField(default=False, verbose_name='Extra preventivo')),
                ('attivita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ore.Attivita')),
            ],
        ),
        migrations.CreateModel(
            name='SchedaLavoro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('attivita_svolte', models.ManyToManyField(related_name='attivita_scheda', through='ore.SchedaAttivita', to='ore.Attivita')),
                ('cantiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cantiere_scheda', to='ore.Cantiere')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dipendente_scheda', to='ore.Dipendente')),
            ],
            options={
                'verbose_name': 'Scheda lavoro',
                'verbose_name_plural': 'Schede lavoro',
            },
        ),
        migrations.AddField(
            model_name='schedaattivita',
            name='scheda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ore.SchedaLavoro'),
        ),
        migrations.AddField(
            model_name='cantiere',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_cantiere', to='ore.Cliente'),
        ),
        migrations.AddField(
            model_name='attivita',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_attivita', to='ore.CategoriaAttivita'),
        ),
    ]
