# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attivita',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cantiere',
            name='descrizione',
            field=models.CharField(max_length=100, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='categoriaattivita',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cognome',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cognome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='cognome',
            field=models.CharField(max_length=30, verbose_name='Cognome'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
    ]
